// Demo data for when MongoDB is unavailable
// This allows the app to work offline for demonstration purposes

export const demoUsers = [
  {
    _id: 'demo-user-1',
    name: 'Demo User',
    email: 'user@demo.com',
    phone: '9876543210',
    role: 'user',
    isActive: true,
    isVerified: true,
  },
  {
    _id: 'demo-user-2',
    name: 'City Hospital Admin',
    email: 'hospital@demo.com',
    phone: '9876543211',
    role: 'hospital',
    isActive: true,
    isVerified: true,
  },
  {
    _id: 'demo-user-3',
    name: 'Super Admin',
    email: 'admin@demo.com',
    phone: '9876543212',
    role: 'admin',
    isActive: true,
    isVerified: true,
  },
];

export const demoHospitals = [
  {
    _id: 'demo-hospital-1',
    userId: 'demo-user-2',
    name: 'City General Hospital',
    registrationNumber: 'HOS-2024-001',
    type: 'government',
    description: 'A leading government hospital providing quality healthcare services to the community with state-of-the-art facilities.',
    address: {
      street: '123 Medical Road, Sector 5',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    location: {
      type: 'Point',
      coordinates: [72.8777, 19.0760],
    },
    contact: {
      phone: '022-12345678',
      emergency: '022-12345679',
      email: 'info@cityhospital.com',
    },
    beds: {
      general: { total: 200, occupied: 150, available: 50 },
      icu: { total: 50, occupied: 35, available: 15 },
      oxygen: { total: 100, occupied: 60, available: 40 },
      ventilator: { total: 30, occupied: 20, available: 10 },
    },
    bloodBank: [
      { bloodGroup: 'A+', units: 25, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'A-', units: 10, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B+', units: 30, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B-', units: 8, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB+', units: 15, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB-', units: 5, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O+', units: 40, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O-', units: 12, lastUpdated: new Date().toISOString() },
    ],
    departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'Gynecology', 'Emergency Medicine'],
    facilities: ['24/7 Emergency', 'Pharmacy', 'Laboratory', 'Radiology', 'Cafeteria', 'Parking', 'Ambulance Service'],
    rating: { overall: 4.2, totalReviews: 156 },
    isOpen24x7: true,
    hasEmergencyServices: true,
    isApproved: true,
    isActive: true,
    lastBedUpdate: new Date().toISOString(),
    lastBloodUpdate: new Date().toISOString(),
  },
  {
    _id: 'demo-hospital-2',
    userId: 'demo-user-2',
    name: 'Apollo Multispecialty Hospital',
    registrationNumber: 'HOS-2024-002',
    type: 'multispecialty',
    description: 'World-class healthcare with cutting-edge technology and expert medical professionals.',
    address: {
      street: '456 Health Avenue, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
    },
    location: {
      type: 'Point',
      coordinates: [72.8296, 19.0596],
    },
    contact: {
      phone: '022-87654321',
      emergency: '022-87654322',
      email: 'care@apollo.com',
    },
    beds: {
      general: { total: 300, occupied: 200, available: 100 },
      icu: { total: 80, occupied: 50, available: 30 },
      oxygen: { total: 120, occupied: 70, available: 50 },
      ventilator: { total: 50, occupied: 30, available: 20 },
    },
    bloodBank: [
      { bloodGroup: 'A+', units: 50, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'A-', units: 20, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B+', units: 45, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B-', units: 15, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB+', units: 25, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB-', units: 10, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O+', units: 60, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O-', units: 25, lastUpdated: new Date().toISOString() },
    ],
    departments: ['Cardiology', 'Oncology', 'Neurosurgery', 'Transplant', 'Gastroenterology', 'Pulmonology', 'Nephrology'],
    facilities: ['24/7 Emergency', 'Pharmacy', 'Laboratory', 'MRI', 'CT Scan', 'PET Scan', 'Cafeteria', 'Valet Parking', 'Helipad'],
    rating: { overall: 4.7, totalReviews: 342 },
    isOpen24x7: true,
    hasEmergencyServices: true,
    isApproved: true,
    isActive: true,
    lastBedUpdate: new Date().toISOString(),
    lastBloodUpdate: new Date().toISOString(),
  },
  {
    _id: 'demo-hospital-3',
    userId: 'demo-user-2',
    name: 'Max Super Specialty Hospital',
    registrationNumber: 'HOS-2024-003',
    type: 'private',
    description: 'Premium healthcare services with personalized care and advanced medical technology.',
    address: {
      street: '789 Wellness Park, Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400069',
    },
    location: {
      type: 'Point',
      coordinates: [72.8697, 19.1136],
    },
    contact: {
      phone: '022-55556666',
      emergency: '022-55556667',
      email: 'info@maxhospital.com',
    },
    beds: {
      general: { total: 150, occupied: 100, available: 50 },
      icu: { total: 40, occupied: 28, available: 12 },
      oxygen: { total: 60, occupied: 40, available: 20 },
      ventilator: { total: 25, occupied: 15, available: 10 },
    },
    bloodBank: [
      { bloodGroup: 'A+', units: 18, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'A-', units: 6, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B+', units: 22, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B-', units: 4, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB+', units: 12, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB-', units: 3, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O+', units: 28, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O-', units: 8, lastUpdated: new Date().toISOString() },
    ],
    departments: ['Cardiology', 'Orthopedics', 'Urology', 'ENT', 'Dermatology', 'Psychiatry'],
    facilities: ['24/7 Emergency', 'Pharmacy', 'Laboratory', 'X-Ray', 'Ultrasound', 'Cafeteria', 'Parking'],
    rating: { overall: 4.5, totalReviews: 198 },
    isOpen24x7: true,
    hasEmergencyServices: true,
    isApproved: true,
    isActive: true,
    lastBedUpdate: new Date().toISOString(),
    lastBloodUpdate: new Date().toISOString(),
  },
  {
    _id: 'demo-hospital-4',
    userId: 'demo-user-2',
    name: 'LifeCare Trauma Center',
    registrationNumber: 'HOS-2024-004',
    type: 'trauma',
    description: 'Specialized trauma and emergency care center with rapid response teams.',
    address: {
      street: '321 Emergency Lane, Dadar',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400014',
    },
    location: {
      type: 'Point',
      coordinates: [72.8426, 19.0178],
    },
    contact: {
      phone: '022-99998888',
      emergency: '022-99998889',
      email: 'emergency@lifecare.com',
    },
    beds: {
      general: { total: 80, occupied: 60, available: 20 },
      icu: { total: 30, occupied: 25, available: 5 },
      oxygen: { total: 40, occupied: 35, available: 5 },
      ventilator: { total: 20, occupied: 18, available: 2 },
    },
    bloodBank: [
      { bloodGroup: 'A+', units: 35, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'A-', units: 15, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B+', units: 40, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B-', units: 12, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB+', units: 20, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB-', units: 8, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O+', units: 55, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O-', units: 30, lastUpdated: new Date().toISOString() },
    ],
    departments: ['Trauma Surgery', 'Emergency Medicine', 'Critical Care', 'Neurosurgery', 'Orthopedic Trauma'],
    facilities: ['24/7 Emergency', 'Trauma ICU', 'Operation Theater', 'Blood Bank', 'Ambulance Fleet', 'Helipad'],
    rating: { overall: 4.8, totalReviews: 89 },
    isOpen24x7: true,
    hasEmergencyServices: true,
    isApproved: true,
    isActive: true,
    lastBedUpdate: new Date().toISOString(),
    lastBloodUpdate: new Date().toISOString(),
  },
  {
    _id: 'demo-hospital-5',
    userId: 'demo-user-2',
    name: 'Sunshine Maternity Hospital',
    registrationNumber: 'HOS-2024-005',
    type: 'maternity',
    description: 'Specialized maternity and women healthcare with experienced gynecologists.',
    address: {
      street: '555 Mother Care Road, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
    },
    location: {
      type: 'Point',
      coordinates: [72.9052, 19.1196],
    },
    contact: {
      phone: '022-77776666',
      emergency: '022-77776667',
      email: 'care@sunshinematernity.com',
    },
    beds: {
      general: { total: 100, occupied: 70, available: 30 },
      icu: { total: 15, occupied: 8, available: 7 },
      oxygen: { total: 20, occupied: 10, available: 10 },
      ventilator: { total: 10, occupied: 4, available: 6 },
    },
    bloodBank: [
      { bloodGroup: 'A+', units: 20, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'A-', units: 8, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B+', units: 25, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'B-', units: 6, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB+', units: 10, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'AB-', units: 4, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O+', units: 30, lastUpdated: new Date().toISOString() },
      { bloodGroup: 'O-', units: 12, lastUpdated: new Date().toISOString() },
    ],
    departments: ['Obstetrics', 'Gynecology', 'Neonatology', 'Pediatrics', 'Fertility'],
    facilities: ['Labor & Delivery', 'NICU', 'Ultrasound', 'Pharmacy', 'Lactation Support', 'Birthing Suites'],
    rating: { overall: 4.6, totalReviews: 267 },
    isOpen24x7: true,
    hasEmergencyServices: true,
    isApproved: true,
    isActive: true,
    lastBedUpdate: new Date().toISOString(),
    lastBloodUpdate: new Date().toISOString(),
  },
];

export const demoDoctors = [
  {
    _id: 'demo-doctor-1',
    hospitalId: 'demo-hospital-1',
    name: 'Dr. Rajesh Kumar',
    specialization: 'Cardiology',
    qualification: 'MD, DM Cardiology',
    experience: 15,
    consultationFee: 800,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    rating: 4.8,
    isActive: true,
  },
  {
    _id: 'demo-doctor-2',
    hospitalId: 'demo-hospital-1',
    name: 'Dr. Priya Sharma',
    specialization: 'Pediatrics',
    qualification: 'MD Pediatrics',
    experience: 10,
    consultationFee: 600,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
    rating: 4.7,
    isActive: true,
  },
  {
    _id: 'demo-doctor-3',
    hospitalId: 'demo-hospital-2',
    name: 'Dr. Anil Mehta',
    specialization: 'Oncology',
    qualification: 'MD, DM Medical Oncology',
    experience: 20,
    consultationFee: 1500,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    rating: 4.9,
    isActive: true,
  },
  {
    _id: 'demo-doctor-4',
    hospitalId: 'demo-hospital-2',
    name: 'Dr. Sunita Rao',
    specialization: 'Neurosurgery',
    qualification: 'MCh Neurosurgery',
    experience: 18,
    consultationFee: 2000,
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    rating: 4.8,
    isActive: true,
  },
  {
    _id: 'demo-doctor-5',
    hospitalId: 'demo-hospital-3',
    name: 'Dr. Vikram Singh',
    specialization: 'Orthopedics',
    qualification: 'MS Orthopedics',
    experience: 12,
    consultationFee: 1000,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    rating: 4.6,
    isActive: true,
  },
  {
    _id: 'demo-doctor-6',
    hospitalId: 'demo-hospital-4',
    name: 'Dr. Arjun Patel',
    specialization: 'Trauma Surgery',
    qualification: 'MS General Surgery, Fellowship in Trauma',
    experience: 14,
    consultationFee: 1200,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    rating: 4.9,
    isActive: true,
  },
  {
    _id: 'demo-doctor-7',
    hospitalId: 'demo-hospital-5',
    name: 'Dr. Kavita Desai',
    specialization: 'Obstetrics & Gynecology',
    qualification: 'MD, DNB OB-GYN',
    experience: 16,
    consultationFee: 900,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    rating: 4.7,
    isActive: true,
  },
];

// Demo password is: Demo@123
export const DEMO_PASSWORD_HASH = '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.wE0R2M.WKX1U9QOOxy';
